# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT
server:
  port: 8081
  address: 0.0.0.0
  forward-headers-strategy: framework

springdoc:
  api-docs:
    server:
      url: "https://issuer-oid4vci.home.rwpz.net"

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: "jdbc:postgresql://localhost:5183/issuer_db"
    username: "issuer_oid4vci_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: create # when starting locally we connect to the db from compose.yml and generate the schema from hibernate
      ddl-auto: validate  # prevent altering tables

logging:
  level:
    ch.admin.bj.swiyu: DEBUG
    org.springframework.web: DEBUG

application:
  issuer-id: "did:tdw:QmVrRb4d1cE1TKmYijhWMNrtp57YvPBr2TSNYNcRLFLzKm:base-registry.home.rwpz.net:api:v1:did:6576ce1c-75bc-4d56-acca-ec3ffa7abd96"
  template-replacement: # Hash Map of Values replaced in the templating
    external-url: "https://issuer-oid4vci.home.rwpz.net"
  token-ttl: 600
  #  openid-file: "file:///data/openid.json"
  openid-file: "classpath:openid.json"
  metadata-file: "classpath:issuer_metadata.json"
  key:
    sdjwt:
      private-key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIAdDBy8cpDJvMq1jVfZo8Q9bBoZ9hZOhAD9MO2D3H7iAoAoGCCqGSM49\nAwEHoUQDQgAEhrMnAcQfayY5/lZYBqvtCLiAFVuEXtlDeMyQQRBMCpWunypG0zq3\nPq528uiDyTxQ4drbMirkGw8zt80JzdW7Wg==\n-----END EC PRIVATE KEY-----\n"
