# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT
server:
  port: 8081
  address: 0.0.0.0

spring:
  docker:
    compose:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5183/issuer_db"
    username: "oid4vci_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # when starting locally we connect to the db from compose.yml and generate the schema from hibernate

logging:
  level:
    ch.admin.bj.swiyu: DEBUG
    org.springframework.web: DEBUG

application:
  issuer-id: "did:tdw:QmRAgGovbs8n3FuUHSt1E88NSmoQ3GYNafuht1wJwfYFLu:base-registry.home.rwpz.net:api:vi:did:f91377d8-90a6-42a6-a239-6a2e3aaa1319"
  template-replacement: # Hash Map of Values replaced in the templating
    external-url: "https://issuer-oid4vci.home.rwpz.net"
  token-ttl: 600
  #  openid-file: "file:///data/openid.json"
  openid-file: "classpath:openid.json"
  metadata-file: "classpath:issuer_metadata.json"
  key:
    sdjwt:
      private-key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIIDWe1M9W8l6454kxiGIdKiRXaJI7tecS9vlgGmgdlPWoAoGCCqGSM49\nAwEHoUQDQgAE/rY0CKKOxHprLXUDKKimBbK1cRXYrLXAs5l1sTMcmu9M3+TPywhm\n3mVrk99WO3sejkmsGBNvoMtX4lZK48tdYw==\n-----END EC PRIVATE KEY-----\n"
